services:
  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:${CFLT_TAG}
    profiles:
      - ksqldb
    hostname: ksqldb-server
    container_name: ksqldb-server
    restart: always
    depends_on:
      - schemaregistry
    ports:
      - 8088:8088
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka1:29092,kafka2:29092,kafka3:29092,kafka4:29092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: true
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: true
      KSQL_KSQL_SERVICE_ID: ksqldb-cluster
      KSQL_KSQL_HIDDEN_TOPICS: ^_.*
      KSQL_KSQL_INTERNAL_TOPIC_REPLICAS: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_STREAMS_REPLICATION_FACTOR: 1
      KSQL_LOG4J_ROOT_LOGLEVEL: INFO
      KSQL_PRODUCER_ENABLE_IDEMPOTENCE: 'true'
      # Schema Registry using HTTP
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schemaregistry:8081
      KSQL_OPTS: "-javaagent:/tmp/jmx_prometheus_javaagent-1.0.1.jar=1234:/tmp/confluent_ksql.yml"
    volumes:
      - $PWD/jmx-exporter/jmx_prometheus_javaagent-1.0.1.jar:/tmp/jmx_prometheus_javaagent-1.0.1.jar
      - $PWD/jmx-exporter/confluent_ksql.yml:/tmp/confluent_ksql.yml