- hosts: localhost
  gather_facts: no
  vars:
    ## These vars can be moved to the inventory
    env: dev
    node_exporter_enabled: false
    relabel_configs_enabled: true
    ##

    # Prometheus exporter ports
    prometheus_node_exporter_port: 9100

    zookeeper_jmxexporter_port: 8079
    kafka_jmxexporter_port: 8080
    schema_registry_jmxexporter_port: 8078
    connect_jmxexporter_port: 8077
    ksqldb_jmxexporter_port: 8076
  tasks:
    - template:
        src: prometheus.yml.j2
        dest: "prometheus-{{env}}.yml"