services:
  zookeeper:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/zookeeper.yml

  kafka1:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

  kafka2:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_broker.yml

  streams-demo:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      JAVA_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_streams.yml

  connect:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/kafka_connect.yml

  schemaregistry:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/confluent_schemaregistry.yml

  ksqldb-server:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KSQL_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/confluent_ksql.yml

  restproxy:
    volumes:
      - $MONITORING_STACK/../shared-assets/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKAREST_OPTS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.20.0.jar=1234:/usr/share/jmx-exporter/confluent_rest.yml

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - $MONITORING_STACK/assets/prometheus/prometheus-config/:/etc/prometheus

  tools:
    volumes:
      - $MONITORING_STACK/librdkafka/helper:/tmp/helper-librdkafka

  librdkafka:
    image: librdkafka-application
    restart: always
    hostname: librdkafka-demo
    container_name: librdkafka-demo
    volumes:
      - $MONITORING_STACK/../../cp-demo/scripts/security:/etc/kafka/secrets
    env_file:
      - $MONITORING_STACK/librdkafka/env_files/demo.env

  node-exporter:
    image: prom/node-exporter:v1.2.2
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)"

  kafka-lag-exporter:
    image: seglo/kafka-lag-exporter:0.7.1
    container_name: kafka-lag-exporter
    hostname: kafka-lag-exporter
    restart: always
    volumes:
      - $MONITORING_STACK/../shared-assets/kafka-lag-exporter:/opt/docker/conf
      - $MONITORING_STACK/assets/security:/etc/kafka/secrets

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=password"
      - "GF_USERS_ALLOW_SIGN_UP=false"
    ports:
      - 3000:3000
    volumes:
      - $MONITORING_STACK/assets/grafana/provisioning/import:/etc/grafana/provisioning
